### ISSUE TITLE
Change to isparta 4 to support for babel 6

### ISSUE THREAD

**Issue by BerndWessels** [ColCh/isparta-instrumenter-loader#4]
Hello
Please change the dependencies to isparta 4 to support babel 6 please.

```
"dependencies": {
  "isparta": "^4.0.0",
```

Thank you
Bernd

**Comment by ColCh** [comment]
Sure, thank you. Fixed
Whoops missed issue number  in commit.

**Comment by BerndWessels** [comment]
@ColCh Hi great thanks. Did you also publish it to NPM ?

**Comment by ColCh** [comment]
Yup. You can try it now: `npm i -D isparta-instrumenter-loader@0.2.2`

**Comment by BerndWessels** [comment]
@ColCh Works great now. Thank you very much.

**Comment by ColCh** [comment]
I should notice. For isparta@4 it's needed to install version **1.0.0** : `npm i -D isparta-instrumenter-loader@1`
