### ISSUE TITLE
isparta-loader

### ISSUE THREAD

**Issue by tleunen** [ColCh/isparta-instrumenter-loader#5]
What's the difference between this repo and this one? https://github.com/deepsweet/isparta-loader

**Comment by tleunen** [comment]
btw upgrading isparta to v4 should be a major upgrade, since isparta 4 is based on babel6 and isparta 3 was on babel 5.
Now this patch update will definitely create issues for Babel 5 projects

**Comment by doctyper** [comment]
Agreed @tleunen, it took a healthy chunk of our afternoon to track down this bump. Major dependency upgrades should not be included in patch bumps.

**Comment by cwelch5** [comment]
+1

**Comment by ColCh** [comment]
oh shi, @tleunen You're right. I will revert isparta update and release it with first major update

**Comment by ColCh** [comment]
@tleunen whats the difference? this one was released earlier. Also, _isparta-instrumenter-loader_ allows you to pass options for _isparta_

**Comment by ColCh** [comment]
@cwelch5 I've reverted isparta version back to 3 in v0.2.3

**Comment by ColCh** [comment]
Thank you guys, sorry for my inattention to semver
