### ISSUE TITLE
strange coverage report generated:

### ISSUE THREAD

**Issue by graingert** [ColCh/isparta-instrumenter-loader#7]
If I have:

``` js
// ./src/B.js

const a = true;

export default class B {
  c() {
    function d() {}

    //

    if (a) {
      d();
    }
  }
}
```

and

``` js
// ./test/b.js
import B from '../src/B.js';

describe('B', function () {
  describe('#c()', function () {
    it('can be called', function () {
      new B().c();
    });
  });
});
```

The coverage error for `[E] if(a)`, moves to the line with the `#c()` method declaration.

**Comment by graingert** [comment]
Note that the error on line 6 should be on line 11
![strange_coverage_placement](https://cloud.githubusercontent.com/assets/413772/13643498/1c07406a-e619-11e5-9c0c-2dbdf13e5740.png)

**Comment by graingert** [comment]
This also happens with a plain function.

``` js
// ./src/B.js

const a = true;

function c() {
  function d() {}

  //

  if (a) {
    d();
  }
}

c();
```

**Comment by ColCh** [comment]
Thanks for reporting. Is this issue related to this loader? Have you checked, is it working for raw isparta setup or not?

**Comment by graingert** [comment]
@ColCh I'm not sure, I've not been able to configure raw isparta outside of karma/webpack.

**Comment by uglow** [comment]
The strange output I get is in the HTML reporter. Note that the `|| []` branch is correctly identified as not being covered, but then all the following lines to the end of the file are highlighted! 

<img width="657" alt="screen shot 2016-03-30 at 2 59 50 pm" src="https://cloud.githubusercontent.com/assets/3990189/14131551/22a23978-f688-11e5-9046-340950c47dba.png">

The actual coverage stats appear to be correct. It is just the highlighting in this HTML report that is wrong.

**Comment by ColCh** [comment]
Guys this package is just a proxy, please report your issues directly to _isparta_. I have nothing to do with these issues, sorry

**Comment by graingert** [comment]
Actually I can repeat this using just isparta https://github.com/douglasduteil/isparta/issues/115

**Comment by ColCh** [comment]
@uglow what about your issue?

**Comment by uglow** [comment]
@ColCh If this package doesn't generate the reports, I'm happy to close and raise at isparta instead.
