### ISSUE TITLE
Is there any way I can set code coverage min level?

### ISSUE THREAD

**Issue by kopach** [ColCh/isparta-instrumenter-loader#8]
I would like to configure my build in that way, that it should fail if code coverage level lower than it's specified. For example, that's how it's done for [grunt-istanbul-coverage](https://github.com/daniellmb/grunt-istanbul-coverage)

```
        coverage: {
            default: {
                options: {
                    thresholds: {
                        'statements': 95,
                        'branches': 90,
                        'lines': 98,
                        'functions':90
                    },
                    dir: 'coverage',
                    root: 'test'
                }
            }
        }
```

**Comment by ColCh** [comment]
Hi. No it's just , use cli istanbul commant, like `istanbul check --lines 90`. It will check lines coverage and exit with ok code or exit with error code if conditions are not met.

However, this module passes options to _isparta_, try to look into _isparta_ source and docs. AFAIK, it doesn't have coverage thresholds too.

**Comment by kopach** [comment]
Hi, thanks for the hint. I've managed to do this in next way.
1) configure `karma-coverage` to generate json file like this:

```
        coverageReporter: {
            dir: './',
            reporters: [
                {type: 'json', subdir: 'coverage'},
            ]
        },
```

2) then use istanbul tool to check coverage thresholds from this json like this:

```
istanbul check-coverage coverage/coverage-final.json --statements 100 --branches 100 --lines 100 --functions 100
```
