### ISSUE TITLE
Coverage reports only coverage on files relevant to given tests

### ISSUE THREAD

**Issue by phun-ky** [ColCh/isparta-instrumenter-loader#9]
With this configuration: https://gist.github.com/phun-ky/989ac6378c8e0104a56e0e1d17ec9830

I get a proper coverage report, but the coverage report is only for the files included/used by the tests, not the entire code base in my project as I expect, so the report is meaningless.

How do I enable the coverage report for my entire project?

**Comment by ColCh** [comment]
Hi. To get coverage for entire project, you can include all source into bundle and run it. You can use `require.context` from webpack api to load all your modules. However, this is pretty hacky 😏 

Also, it seems that this solution works pretty well:
https://github.com/karma-runner/karma-coverage/issues/192#issuecomment-202215907
You need to swap this module out with `isparta-loader`
